[workspace]

members = [
    "bcm2711",
    "bcm2711-hal",
    "raspi3_boot",
    "examples/uart0",
    "examples/uart1",
    "examples/mbox",
    "examples/embedded-graphics",
    "examples/analog-clock",
    "examples/eth",
    "examples/mem2mem-dma",
]
