[package]
name = "rtp-h264-decoder"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"

[dependencies]

[dependencies.rtp]
path = "../rtp"

[dependencies.byteorder]
version = "1.3"
default-features = false

[dependencies.log]
version = "0.4"
default-features = false
